# Short course - Numpy

In [1]:
import numpy as np

The core of the `numpy` package is the `array` class. Let's examine that first. We can make an array out of a sequence, like a list.

In [2]:
d = [1, 2, 3, 4, 5]
np.array(d)

array([1, 2, 3, 4, 5])

### data types

Unlike lists, arrays must be homogeneous, in that the data types of each element must be the same. The data type of the array us upcast to be able to represent all of the data. So, if only one element is a float, all elements will be converted to floats.

In [3]:
d = [1, 2, 3.1415, 4, 5]
np.array(d)

array([ 1.    ,  2.    ,  3.1415,  4.    ,  5.    ])

You can query the datatype by examaning the dtype attribute of the array.

In [4]:
d = [1, 2, 3.1415, 4, 5]
arr = np.array(d)
arr.dtype

dtype('float64')

Array types may be defined explicity in the call

In [5]:
arr = np.array([1, 2, 3, 4, 5], dtype='float32')
arr

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

Complex numbers are noted with a lowercase `j` or uppercase `J`, like this

In [6]:
cmplx = np.array([1.0+2.0j, 3.0+4.0J])
print(cmplx)
cmplx.dtype

[ 1.+2.j  3.+4.j]


dtype('complex128')

As we have seen before, arrays are like multidimensional sequences. We can create a 2D array by supplying a list of lists as the argument.

In [7]:
arr = np.array([[1., 2., 3.,], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [8]:
import numpy as np

The core of the `numpy` package is the `array` class. Let's examine that first. We can make an array out of a sequence, like a list.

In [9]:
d = [1, 2, 3, 4, 5]
np.array(d)

array([1, 2, 3, 4, 5])

### data types

Unlike lists, arrays must be homogeneous, in that the data types of each element must be the same. The data type of the array us upcast to be able to represent all of the data. So, if only one element is a float, all elements will be converted to floats.

In [10]:
d = [1, 2, 3.1415, 4, 5]
np.array(d)

array([ 1.    ,  2.    ,  3.1415,  4.    ,  5.    ])

You can query the datatype by examaning the dtype attribute of the array.

In [11]:
d = [1, 2, 3.1415, 4, 5]
arr = np.array(d)
arr.dtype

dtype('float64')

Array types may be defined explicity in the call

In [12]:
arr = np.array([1, 2, 3, 4, 5], dtype='float32')
arr

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

Complex numbers are noted with a lowercase `j` or uppercase `J`, like this

In [13]:
cmplx = np.array([1.0+2.0j, 3.0+4.0J])
print(cmplx)
cmplx.dtype

[ 1.+2.j  3.+4.j]


dtype('complex128')

As we have seen before, arrays are like multidimensional sequences. We can create a 2D array by supplying a list of lists as the argument.

In [14]:
arr = np.array([[1., 2., 3.,], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

### Array attributes

Arrays have a few other important attributes. Note attributes never have paretheses after them. Methods always do.

In [15]:
arr.size          # The number of elements in the array

6

In [16]:
arr.shape         # The shape of the array (i.e., the size of each dimension)

(2, 3)

In [17]:
arr.ndim          # The number of dimensions of the array

2

### Setting array shape

You can set the `array.shape` attribute to change the shape of the array. This attribute does not change the elements of the array, or how it is stored in memory, just how it is seen.

In [18]:
arr.shape = (3, 2)
arr

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [19]:
arr.shape = (6,)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.])

Singleton dimensions add to the dimensionality of an array. The last example was a 1D array, the next are 2D arrays.

In [20]:
arr.shape = (1, 6)
arr   # Note that there are *two* square brackets in the output sequence.

array([[ 1.,  2.,  3.,  4.,  5.,  6.]])

In [21]:
arr.shape = (6, 1)
arr   # this is also a 2D array, like a column vector

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.]])

## Array indexing

Arrays are indexed in a similar way to sequences, with `start:stop:stride` notation. Except that this is used for each dimension in the array. Colons denote all the values in a particular dimension, slices indicate some particular subset of the data in that particular dimension. 

A common use case is to get a single row or column from a 2D array (a table of data).

In [22]:
arr = np.arange(60).reshape(6, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [23]:
arr[:, 4]   # the 5th column

array([ 4, 14, 24, 34, 44, 54])

In [24]:
arr[2, :]   # the 3rd row

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
arr[2]     # Trailing colons do not need to be explicitly typed. This is equivalent to the last example.

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
arr[4, 7]   # an indvidual element in the table

47

Slices can be combined in any way. Here we take ever other rho and the fourth+ column

In [27]:
a = np.arange(20).reshape(4, 5)
a[::2, 3:]

array([[ 3,  4],
       [13, 14]])

### Conventions concerning arrays containing spatio-temporal information

Generally, you will want to think of arrays as representing dimensions in space and time. The conventional way to think of this is that the dimensions are $(t, z, y, x)$; missing dimensions are omitted. This will help make plotting and analysis easier. Some examples might be:

    temp[:, :, :, :]     # A 4D array (time, height, latitude, longitude)
    press[:, :]          # A 2D array (time, height)
    humid[:, :]          # A 2D array (latitude, longitude)

## Array methods

Arrays have a number of methods. Let's take a look at the 'mean' method as an example. 

In [28]:
arr = np.array([[1., 2., 3.,], [4., 5., 6.]])  # reset the array to our 2x3 array.

arr.mean()        # The mean of all of the elements in the array

3.5

Mean takes the optional argument `axis` that can be used to take the mean along a single axis of the array. Just like with indexing, the axes are reference in a zero-based system; `axis=0` means the first dimension. 

In [29]:
arr.mean(axis=0)  # The mean 

array([ 2.5,  3.5,  4.5])

In this case, there are two rows in the first dimension, and `arr.mean(axis=0)` takes the average in the 'row' direction, resulting in a 1D array that is the average of each column.

---
### *Exercise*

> Find the mean of the array in the 'column' direction, along `axis=1`.

> Use the `sum` method of the array class to get the sum of the numbers in each column. The result should be a 1D array with three elements.

---

You can also use the `reshape` method to change the shape of an array.

In [30]:
arr.reshape(3,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

You can find the mininum and maximum of an array with the `min` and `max` methods. Sometimes it is useful to find the indices of these minima and maxima. For this use `argmin` and `argmax`, like

In [31]:
x = np.random.rand(10)
imax = x.argmax()
print(imax, x[imax], x.max())

2 0.87920255534 0.87920255534


## Vectorization

The best way to do mathematical operations using numpy arrays is to do `vector` operations. That is, mathematical operations are defined to be element by element, and this is done much faster than looping. As a rule of thumb, you should be very concerned if your code has more than one significant `for` loop in the numerical analysis section.

In [32]:
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

sol = a * b       # element-by-element multiplication. This operation is about as fast as it can be on your computer.

### Ufuncs

`Ufunc`s or Universal functions are ways to apply a function to every element in the array. Let's check the Euler relation.

In [33]:
a = np.random.rand(3, 4, 5)

res1 = np.exp(1.0J*a).real    # The `real` attribute returns the real part of a complex number
res2 = np.cos(a)

np.allclose(res1, res2)       # Checks if all of the elements are close, within some small tolerance.

True

## Array broadcasting

Arrays may be operated on using vector operations even if they are different sized, however, they need to follow the rules of `array broadcasting`.  One way to think of this is that a larger dimension will be 'broadcast' across a singleton dimension. Generally, all of the dimensions need to be either the same size, or one of the dimension sizes for a particular dimension should be of size 1. Arrays always have as many 'singleton' dimensions to the left as needed.  For example, these arrays will all 'broadcast'

      a: 5 x 7 x 1 x 8
      b:             8
      c:     7 x 3 x 8
      d: 5 x 1 x 3 x 1
    
    sol: 5 x 7 x 3 x 8   

Let's create these arrays with random numbers

In [34]:
a = np.random.rand(5, 7, 1, 8)
b = np.random.rand(8)
c = np.random.rand(7, 3, 8)
d = np.random.rand(5, 1, 3, 1)
print(a.shape, b.shape, c.shape, d.shape)

sol = a * b * c * d
print(sol.shape)

(5, 7, 1, 8) (8,) (7, 3, 8) (5, 1, 3, 1)
(5, 7, 3, 8)


---
### *Exercise*

> Experiment with multiplying just two of the arrays together. Try to predict the resulting shape.

---

Array broadcasting sometimes requires creating new singleton dimensions in arrays. This can be done by putting `np.newaxis` in the appropriate space when indexing the array. For example

In [35]:
x = np.arange(6)   # a 1D array. shape (6,)

x1 = x[:, np.newaxis]   # 2D array, shape (6, 1)
x2 = x[np.newaxis, :]   # 2D array, shape (1, 6)

np.abs(x1 - x2)  # A 'distance' matrix, a 2D array, shape (6, 6)

array([[0, 1, 2, 3, 4, 5],
       [1, 0, 1, 2, 3, 4],
       [2, 1, 0, 1, 2, 3],
       [3, 2, 1, 0, 1, 2],
       [4, 3, 2, 1, 0, 1],
       [5, 4, 3, 2, 1, 0]])

## Creating standard arrays

There are a few standard arrays, for example, arrays filled with zeros or ones (or empty). Here are some examples of creating arrays

In [36]:
o = np.ones((3, 4, 5))    # The argument is a shape, so is a tuple with the length of each dimension as an argument
b = np.ones((2, 3), dtype=np.bool)
z = np.zeros((2, 3), dtype=np.float32)

b

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

You can also create these arrays with the same shape and datatype of the input array using `np.ones_like` and `np.zeros_like`.

In [37]:
zb = np.zeros_like(b)
zb

array([[False, False, False],
       [False, False, False]], dtype=bool)

You can also create a diagonal array with a given vector along the diagonal. These can be offset with an optional argument `k` (default=0). This example creates a tri-diagonal array similar to that used for finite difference calculations

In [38]:
np.diag(-2*np.ones(6)) + np.diag(np.ones(5), k=-1) + np.diag(np.ones(5), k=1)

array([[-2.,  1.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  1., -2.]])

There are also a number of ways to generate sequences of numbers.
 - `np.arange([start,] stop [[, stride]])` Create a sequence of numbers, similar to `range`
 - `np.linspace(min, max, length)` Create a uniform series of specified `length` between `min` and `max`, inclusive.
 - `np.logspace(minpow, maxpow, length)` Create a uniform series in logspace of specified `length` between `10**minpow` and `10**maxpow`, inclusive.
 

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [41]:
np.linspace(2, 4, 17)

array([ 2.   ,  2.125,  2.25 ,  2.375,  2.5  ,  2.625,  2.75 ,  2.875,
        3.   ,  3.125,  3.25 ,  3.375,  3.5  ,  3.625,  3.75 ,  3.875,  4.   ])

In [42]:
np.logspace(-2, 2, 9)

array([  1.00000000e-02,   3.16227766e-02,   1.00000000e-01,
         3.16227766e-01,   1.00000000e+00,   3.16227766e+00,
         1.00000000e+01,   3.16227766e+01,   1.00000000e+02])

## Finding values

There are a number of ways to find values in an array. The simplest is always to create a boolean array, like

In [43]:
x = np.random.rand(5, 5)
print(x)
ind = x > 0.5
print(ind)

[[ 0.65116738  0.88516894  0.34435557  0.30385285  0.92305112]
 [ 0.42381332  0.41808357  0.75890381  0.67046589  0.87308826]
 [ 0.24026648  0.43385647  0.81556911  0.68794782  0.681364  ]
 [ 0.11298466  0.65980007  0.2848843   0.68969782  0.80469751]
 [ 0.392325    0.40937256  0.90896886  0.902267    0.64964939]]
[[ True  True False False  True]
 [False False  True  True  True]
 [False False  True  True  True]
 [False  True False  True  True]
 [False False  True  True  True]]


The boolean array can be used as an index to other arrays. Note this will return a 1D array, no matter what dimension the origial arrays are, because there is no way to know what structure the true values have.

In [44]:
x = np.random.rand(5, 5)
y = np.sin(x)

y[x > 0.5]
# or, equivalently, as two lines
# idx = x > 0.5
# y[idx]

array([ 0.72185801,  0.77840975,  0.72396575,  0.57628469,  0.71822638,
        0.77052199,  0.59216209,  0.7899892 ,  0.52493155,  0.59002833,
        0.50083822,  0.83503392,  0.83811538])

To get the indices of the places where the conditional is true (i.e., the locations of the `True` values in the boolean array), use the `np.where` command. 

In [45]:
x = np.random.rand(5, 5)
idx = np.where(x > 0.5)
idx

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]),
 array([0, 2, 4, 0, 1, 2, 0, 3, 4, 2, 3, 4, 1]))

Note that `np.where` ~always returns a tuple of indices for each dimension. This is a little strange for 1D arrays, but is done for consistancy across all input values. Often, you will want to explicitly pull out the (single) array of indices from the tuple, like

In [46]:
x = np.random.rand(10)
idx = np.where(x>0.5)[0]
print(idx)

[4 5 6 7 9]


_What happens with the [0] is missing behind the call to `where`?_

---
### *Exercise*

> You can also use these calculated indices, or boolean matricies on the left hand side for assignment.

> Create a 10x10 random array, with values between 0 and 1. Replace all of the numbers smaller than 0.5 with zero.

---

## Importing data

One of the basic commands in numpy for loading in data is the `loadtxt` command. There are other ways to do this, such as the [`genfromtxt`](http://docs.scipy.org/doc/numpy-dev/user/basics.io.genfromtxt.html) command, but `loadtxt` is sufficient for most purposes, and is easy to use.

In [47]:
data = np.loadtxt('03_CTD.dat', comments='*')
data[:,2]    # a column of data representing temperature

array([ 26.5827,  25.9263,  25.3695,  25.2304,  24.568 ,  24.6885,
        24.7855,  24.7213,  24.5692,  24.3945,  24.3252,  24.2424,
        24.1822,  24.1057,  23.9863,  23.9235,  23.8288,  23.7446,
        23.6302,  23.711 ,  23.6082,  23.4458,  23.4764,  23.4612,
        23.4353,  23.4063,  23.358 ,  23.3041,  23.2337,  23.1621,
        23.1239,  23.045 ,  23.0066,  22.9947,  22.9833,  22.9804,  22.9798])